# Generated by Django 2.1.7 on 2020-01-07 08:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200107_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='price',
        ),
        migrations.AddField(
            model_name='emp',
            name='doj',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
